# -*- coding: utf-8 -*-
"""taller_21.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/17CL4MjRtUiCqPpvgT3x2aJ4hOC7Yf_u5
"""

import numpy

x = numpy.array([1, 3, 5, 7, 9, 11, 13])
y = numpy.array([7.4, 1.8, -1, -1.8, -1.2, 2.2, 7.2])

coefficients = numpy.polyfit(x, y, 2)
poly = numpy.poly1d(coefficients)

y_pred = poly(x)

r = numpy.corrcoef(x, y)[0, 1]
print("Coeficientes del polinomio:", coefficients)
print("Coeficiente de correlación (r):", r)