# -*- coding: utf-8 -*-
"""Taller_17.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/18k_GC6jWdId74WVxhmyjJGIXPNv1rEN-
"""

import numpy as np
import matplotlib.pyplot as plt

def regression_lineal(x, y):
    x = np.array(x)
    y = np.array(y)

    n = len(x)

    sum_x = np.sum(x)
    sum_y = np.sum(y)
    sum_xy = np.sum(x * y)
    sum_x_squared = np.sum(x**2)

    m = (n * sum_xy - sum_x * sum_y) / (n * sum_x_squared - sum_x**2)
    b = (sum_y - m * sum_x) / n

    return m, b

x_valores = input("Introduce los valores de x separados por espacios: ").split()
y_valores = input("Introduce los valores de y separados por espacios: ").split()

x_valores = [float(valor) for valor in x_valores]
y_valores = [float(valor) for valor in y_valores]

m, b = regression_lineal(x_valores, y_valores)

print(f"La ecuación de la recta ajustada es: y = {m:.2f}x + {b:.2f}")

x_fit = np.linspace(min(x_valores), max(x_valores), 100)
y_fit = m * x_fit + b

plt.scatter(x_valores, y_valores, label='Datos')
plt.plot(x_fit, y_fit, color='red', label='Ajuste Lineal')
plt.xlabel('x')
plt.ylabel('y')
plt.title('Regresión Lineal por Mínimos Cuadrados')
plt.legend()
plt.grid(True)
plt.show()